# Site settings
title: Aasim Mohammed - About Me
description: Aasim

# Site settings
description: Aasim Mohammed - About Me
baseurl: "/"


# User settings
username: Aasim
user_description: Second-year Computer Science Undergraduate Student with a yearning for something more...
user_title: Wannabe Tech Expert
email: aasim.mo10@gmail.com
linkedin_username: https://linkedin.com/in/aasim-m
github_username: https://github.com/AasimMo

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
