# Site settings
title: Aasim Mohammed - Bio
description: Aasim
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# Site settings
description: Aasim Mohammed - Bio
baseurl: "/" # the subpath of your site, e.g. /blog/
#url: "http://localhost:3000" # the base hostname & protocol for your site


# User settings
username: Aasim
user_description: Second-year Computer Science Undergraduate Student with a yearning for something more...
user_title: Wannabe Tech Expert
email: aasim.mo10@gmail.com
linkedin_username: https://linkedin.com/in/aasim-m
github_username: https://github.com/AasimMo

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
